### ISSUE TITLE
Main Interface Design & Implementation

### ISSUE THREAD

**Issue by ghost** [GDProgramming/IRC-Sharp#5]
We need to get the main message area, user list, input bar (for messages etc.) in on the main window as quickly as possible so we can begin sending commands through the interface

You'll need to use Blend/interfacebuilder or code xaml yourself for this. If you're not sure how to do it, I recommend looking up a tutorial.

It doesn't have to be too complex for now. Placeholders are fine.

**Comment by ghost** [comment]
Could also use a toolbar at the top - handle connections, server browser, friend/block lists, etc.

**Comment by TommyAGK** [comment]
Made a pull request with a basic rough design
